trigger:
 - master
 
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
    
steps:
- script: |
    echo ${{ variables.one }} # outputs initialValue
    echo $(one)
  displayName: First variable pass

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'restore'
#    feedsToUse: 'select'
#    vstsFeed: 'my-vsts-feed' # A series of numbers and letters

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    arguments: '--configuration $(buildConfiguration)'
#  displayName: 'dotnet build $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: test
#    projects: '**/*Tests/*.csproj'
#    arguments: '--configuration $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: test
#    projects: '**/*Tests/*.csproj'
#    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

# Publicar artefatos no Azure
#- task: DotNetCoreCLI@2
#  inputs:
#    command: publish
#    publishWebProjects: True
#    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#    zipAfterPublish: True

#- task: PublishBuildArtifacts@1
#  inputs:
#    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
#    artifactName: 'FamilyTreeExampleCI'
